import "../styles/globals.scss";
import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import { useLocale } from "next-intl";
import { notFound } from "next/navigation";

const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "Create Next App",
    description: "Generated by create next app",
    url: "https://create-next-app.com",
    siteName: "Create Next App",
  },
  robots: {},
};

interface LayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export default function RootLayout({ children, params }: LayoutProps) {
  const locale = useLocale();

  if (params.locale !== locale) {
    notFound();
  }
  return (
    <html lang={locale}>
      <body className={urbanist.className}>{children}</body>
    </html>
  );
}
