export const productTitleData = [
  {
    id: 16,
    en: "77 Fitness branded hat",
    ru: "Фирменная шапка 77 Fitness",
    sk: "77 Fitness značková čiapka",
  },
  {
    id: 17,
    en: "77 Fitness branded t-shirt",
    ru: "Фирменная футболка 77 Fitness",
    sk: "77 Fitness značkové tričko",
  },
  {
    id: 18,
    en: "77 Fitness branded shaker",
    ru: "Фирменный шейкер 77 Fitness",
    sk: "77 Fitness značkový shaker",
  },
  {
    id: 19,
    en: "1 Month membership",
    ru: "Абонемент на 1 месяц",
    sk: "Členstvo na 1 mesiac",
  },
  {
    id: 20,
    en: "3 Month membership",
    ru: "Абонемент на 3 месяца",
    sk: "Členstvo na 3 mesiace",
  },
  {
    id: 21,
    en: "6+1 Month membership",
    ru: "Абонемент на 6+1 месяцев",
    sk: "Členstvo na 6+1 mesiacov",
  },
  {
    id: 22,
    en: "1 Year membership",
    ru: "Абонемент на 1 год",
    sk: "Členstvo na 1 rok",
  },
  { id: 25, en: "test", ru: "test", sk: "test" },
];

export const productDescriptionData = [
  {
    id: 16,
    en: "Branded 77Fitness hat",
    ru: "Брендированная кепка 77Fitness",
    sk: "Značková čiapka 77Fitness",
  },
  {
    id: 17,
    en: "Oversized gym t-shirt",
    ru: "Футболка для спортзала большого размера",
    sk: "Nadrozmerné tričko do posilňovne",
  },
  {
    id: 18,
    en: "Shaker for Protein drinks (500ml)",
    ru: "Шейкер для протеиновых напитков (500 мл)",
    sk: "Šejker na proteínové nápoje (500 ml)",
  },
  {
    id: 19,
    en: "Unlimited gym access for 30 days",
    ru: "Неограниченный доступ в тренажерный зал на 30 дней",
    sk: "Neobmedzený prístup do posilňovne no 30 dní",
  },
  {
    id: 20,
    en: "Unlimited gym access for 90 days",
    ru: "Безлимитный доступ в тренажерный зал на 90 дней",
    sk: "Neobmedzený prístup do posilňovne na 90 dní",
  },
  {
    id: 21,
    en: "Unlimited gym access for 210 days",
    ru: "Безлимитный доступ в тренажерный зал на 210 дней",
    sk: "Neobmedzený prístup do posilňovne na 210 dní",
  },
  {
    id: 22,
    en: "Unlimited gym access for 365 days",
    ru: "Безлимитный доступ в тренажерный зал на 365 дней",
    sk: "Neobmedzený prístup do posilňovne na 365 dní",
  },
  { id: 25, en: "test", ru: "test", sk: "test" },
];

export const productData = [
  {
    id: 16,
    sku: "302CF334E7",
    name: "77Fitness Hat",
    categoryId: 8,
    newPrice: 29,
    oldPrice: 32,
    createdAt: new Date("2024-05-23T22:32:36.987Z"),
    toDisplay: true,
    leftInStock: 20,
    descriptionId: 16,
    titleId: 16,
  },
  {
    id: 17,
    sku: "65F091046C",
    name: "77 Fitness T-shirt",
    categoryId: 8,
    newPrice: 29,
    oldPrice: 35,
    createdAt: new Date("2024-05-25T10:38:45.770Z"),
    toDisplay: true,
    leftInStock: 20,
    descriptionId: 17,
    titleId: 17,
  },
  {
    id: 18,
    sku: "D053DCA0D4",
    name: "77 Fitness Shaker",
    categoryId: 8,
    newPrice: 29,
    oldPrice: 32,
    createdAt: new Date("2024-05-25T10:40:24.362Z"),
    toDisplay: true,
    leftInStock: 20,
    descriptionId: 18,
    titleId: 18,
  },
  {
    id: 19,
    sku: "CBDC14DB23",
    name: "1 Month Membership",
    categoryId: 9,
    newPrice: 69,
    oldPrice: 0.01,
    createdAt: new Date("2024-05-25T12:12:59.919Z"),
    toDisplay: true,
    leftInStock: 100,
    descriptionId: 19,
    titleId: 19,
  },
  {
    id: 21,
    sku: "4E4BDCF832",
    name: "3 Month membership",
    categoryId: 9,
    newPrice: 180,
    oldPrice: 0.01,
    createdAt: new Date("2024-05-25T18:03:21.027Z"),
    toDisplay: true,
    leftInStock: 200,
    descriptionId: 20,
    titleId: 20,
  },
  {
    id: 22,
    sku: "9F83982F8C",
    name: "6 + 1 Month Membership",
    categoryId: 9,
    newPrice: 340,
    oldPrice: 483,
    createdAt: new Date("2024-05-25T18:20:43.068Z"),
    toDisplay: true,
    leftInStock: 200,
    descriptionId: 21,
    titleId: 21,
  },
  {
    id: 23,
    sku: "929A07E388",
    name: "Year membership",
    categoryId: 9,
    newPrice: 650,
    oldPrice: 0.01,
    createdAt: new Date("2024-05-25T18:38:37.243Z"),
    toDisplay: true,
    leftInStock: 100,
    descriptionId: 22,
    titleId: 22,
  },
  {
    id: 26,
    sku: "BC08896CBA",
    name: "test",
    categoryId: 9,
    newPrice: 1,
    oldPrice: 0.01,
    createdAt: new Date("2024-05-25T22:07:51.716Z"),
    toDisplay: true,
    leftInStock: 10,
    descriptionId: 25,
    titleId: 25,
  },
];

export const productImagesData = [
  { id: 28, url: "qso2ilbc0ym3t0edzbre", productId: 16 },
  { id: 29, url: "zyi0pshrlxr4lg7corrt", productId: 17 },
  { id: 30, url: "dlykbhtoowc63y61xq1j", productId: 18 },
  { id: 31, url: "bpgoyhdhjdzkj7xndku6", productId: 19 },
  { id: 32, url: "md0tmgu6ddk5ywfx7imq", productId: 21 },
  { id: 33, url: "v5czg9iaynewrj8ekfjx", productId: 22 },
  { id: 34, url: "v5czg9iaynewrj8ekfjx", productId: 23 },
  { id: 37, url: "x9i2n1ifamgdu8eyrefr", productId: 26 },
];
